Repository Nexenta/edgefs, pull requests merged in 2019-10, with the labels that each got.

#381 Ccow cache fixes
  src/ccow/include/ccow.h
  src/ccow/src/libccow/ccow-impl.h
  src/ccow/src/libccow/ccow.c
  src/ccow/src/libchunk/cmcache.c
  src/ccow/src/libreptrans/getcommon_server.c
  src/ccow/src/libreptrans/named-put.c
  src/ccow/src/libreptrans/reptrans.c
  src/ccow/src/libreptrans/rtkvs/reptrans-kvs.c
  src/ccow/src/libreptrans/unnamed-put.c
  src/ccow/src/libreptrans/verify.c
  src/efscli/config/config.go
Labels: approved, size/L

#382 Fix SOP sharded list attributes processing
  src/ccow/src/libccow/ccow-impl.h
  src/ccow/src/libccow/put.c
  src/ccow/src/libccow/sharded-list.c
  src/ccow/src/libreptrans/serial_op.c
  src/ccow/test/basic_fs_ops_test.c
Labels: size/L

#384 Add support openssl-1.1.x.
  src/ccow/src/libcrypto/crypto.c
  src/ccow/src/libreptrans/rtlfs/payload-s3.c
  src/ccowhttpd/sig4auth.c
Labels: approved, size/M

#388 Fix object expunge transaction log flow
  src/ccow/src/libccowd/trput.c
Labels: approved, size/XS

#389 Issue 222
  src/ccow/include/ccow.h
  src/ccow/src/libccow/ccow-impl.h
  src/ccow/src/libccow/ccow.c
  src/ccow/src/libccow/get.c
  src/ccow/src/libccow/named-get.c
  src/ccow/src/libccow/put.c
  src/ccow/src/libccow/snapview.c
  src/ccow/src/libccow/unnamed-get.c
  src/ccow/src/libccowd/trput.c
  src/ccow/src/libccowfsio/fsio_inode.c
  src/ccow/src/libchunk/btree/libbtreenam/btreenam.c
  src/ccow/src/libreplicast/replicast.h
  src/ccow/src/libreptrans/Makefile.am
  src/ccow/src/libreptrans/compat.c
  src/ccow/src/libreptrans/compat.h
  src/ccow/src/libreptrans/erasure-coding.c
  src/ccow/src/libreptrans/named-put.c
  src/ccow/src/libreptrans/reptrans-data.c
  src/ccow/src/libreptrans/reptrans-data.h
  src/ccow/src/libreptrans/reptrans.c
  src/ccow/src/libreptrans/rtkvs/reptrans-kvs.c
  src/ccow/src/libreptrans/rtlfs/reptrans-lfs.c
  src/ccow/src/libreptrans/rtrd/reptrans-rd.c
  src/ccow/src/libreptrans/verify.c
  src/ccow/test/Makefile.am
  src/ccow/test/clone_test.c
  src/ccow/test/get_test.c
  src/ccow/test/put_file.c
  src/ccow/test/reptrans_standalone_test.c
  src/ccow/test/versions_test.c
  src/efscli/main.go
  src/efscli/object/clone.go
  src/efscli/snapshot/add.go
  src/efscli/snapshot/clone.go
  src/efscli/snapshot/list.go
  src/efscli/snapshot/rm.go
  src/efscli/snapshot/rollback.go
  src/efscli/snapshot/snapshot.go
  src/efscli/snapshot/snapview-create.go
  src/efscli/snapshot/snapview-delete.go
Labels: approved, size/XXL

#390 btreenam: SOP fix
  src/ccow/src/libchunk/btree/libbtreenam/btreenam.c
Labels: approved, size/XS

#392 reverted copy_opts.version_vm_content_hash_id
  src/ccow/include/ccow.h
  src/ccow/src/libccow/put.c
  src/ccow/src/libccow/snapview.c
  src/ccow/src/libccowfsio/fsio_inode.c
  src/ccow/test/clone_test.c
  src/ccow/test/put_file.c
  src/ccow/test/versions_test.c
Labels: size/S

#391 Prevent creation of a cluster if system isn't initialized
  src/efscli/cluster/create.go
Labels: size/S

#400 Pass segment id to isgw service
  src/ccow/src/libccow/ccow-dynamic-fetch.c
  src/ccow/src/libccow/ccow-dynamic-fetch.h
  src/ccow/src/libccow/unnamed-get.c
Labels: approved, size/XS

#402 A delete VM get fix
  src/ccow/src/libccow/unnamed-get.c
Labels: approved, size/XS
