Repository Nexenta/edgefs, pull requests merged in 2019-11, with the labels that each got.

#406 Add listing cache for nfs listings of s3 objects
  src/ccow/include/ccowutil.h
  src/ccow/src/libccowfsio/Makefile.am
  src/ccow/src/libccowfsio/fsio_inode.c
  src/ccow/src/libccowfsio/fsio_listcache.c
  src/ccow/src/libccowfsio/fsio_namespace.c
  src/ccow/src/libccowfsio/fsio_s3_transparency.c
  src/ccow/src/libccowfsio/fsio_s3cache.c
  src/ccow/src/libccowfsio/fsio_s3cache.h
  src/ccow/src/libccowfsio/fsio_system.c
  src/ccow/src/libccowfsio/include/fsio_inode.h
  src/ccow/src/libccowfsio/include/fsio_s3_transparency.h
  src/ccow/src/libccowfsio/include/fsio_system.h
Labels: approved, size/XL

#408 REPLIES_CNT() should check if sync_put_named is greater than 1.
  src/ccow/src/libccow/getcommon_client.h
Labels: approved, size/XS

#410 Extract nodename out of CNAME. Drop "."
  src/efscli/config/config.go
Labels: approved, size/XS

#411 Issue 383
  src/ccow/include/ccowfsio.h
  src/ccow/src/libccowfsio/fsio_inode.c
  src/ccow/src/libccowfsio/fsio_recovery.c
  src/ccow/test/basic_fs_bvt.c
Labels: approved, size/L

#413 Issue 407
  env.sh
  src/ccow/src/libccowd/ccowd.c
  src/ccow/src/libccowd/serverid.c
  src/ccow/src/libreplicast/replicast.c
  src/ccow/src/libreptrans/reptrans.c
  src/ccow/src/libreptrans/rtrd/reptrans-rd.c
  src/ccow/src/libreptrans/rtrd/reptrans-rd.h
  src/ccow/test/reptrans_standalone_test.c
  src/ccow/tools/ecstat.c
Labels: size/XL

#414 Followup fix for nfs listings of s3 objects
  src/ccow/src/libccowfsio/fsio_namespace.c
Labels: approved, size/XS

#416 Decrease ccowhttpd stack size to 16M
  src/ccowhttpd/ccowhttpd.c
Labels: size/XS

#420 Followup fix for nfs listings of s3 objects
  src/ccow/src/libccowfsio/fsio_namespace.c
Labels: size/XS

#419 More verbosity for VBR replication errors
  src/ccow/src/libreptrans/ngrequest-send.c
  src/ccow/src/libreptrans/reptrans.c
Labels: approved, size/XS

#424 A delete VM get reflist fix
  src/ccow/src/libccow/unnamed-get.c
Labels: size/S

#430 Rtrd s3offload
  src/ccow/src/libccow/named-put.c
  src/ccow/src/libreptrans/Makefile.am
  src/ccow/src/libreptrans/payload-s3.c
  src/ccow/src/libreptrans/payload-s3.h
  src/ccow/src/libreptrans/reptrans-device.h
  src/ccow/src/libreptrans/reptrans.c
  src/ccow/src/libreptrans/reptrans.h
  src/ccow/src/libreptrans/rtlfs/Makefile.am
  src/ccow/src/libreptrans/rtlfs/reptrans-lfs.c
  src/ccow/src/libreptrans/rtrd/reptrans-rd.c
  src/ccow/src/libreptrans/rtrd/reptrans-rd.h
  src/ccow/src/libreptrans/unnamed-put.c
  src/ccow/tools/dbi_util.c
  src/efscli/config/layout.go
Labels: size/XL

#428 issue-426: disable rdhold in Docker
  src/ccow/src/libreptrans/rtrd/reptrans-rd.c
Labels: size/XS

#429 Issue-425: added vdevstore locking to flexhash_fhserver_vdevs()
  src/ccow/src/libflexhash/flexhash.c
Labels: size/XS

#431 S3-offload followup fix
  src/ccow/src/libreptrans/unnamed-put.c
Labels: approved, size/XS
