Repository Nexenta/edgefs, pull requests merged in 2019-08, with the labels that each got.

#338 Implement s3x objects expiration support
  src/ccowhttpd/ccowhttpd.c
  src/ccowhttpd/ccowobj.c
  src/ccowhttpd/libauth/Makefile
  src/ccowhttpd/libauth/bucket_options.c
  src/ccowhttpd/libauth/bucket_options.h
  src/ccowhttpd/libauth/json_test.c
  src/ccowhttpd/objio.c
  src/ccowhttpd/objio.h
  src/ccowhttpd/param.c
  src/ccowhttpd/param.h
  src/ccowhttpd/request_util.c
  src/ccowhttpd/session.c
  src/ccowhttpd/session.h
Labels: approved, size/XL

#340 Common reptrans drivers bug in a dupsort iterator
  src/ccow/src/libreptrans/rtkvs/reptrans-kvs.c
  src/ccow/src/libreptrans/rtlfs/reptrans-lfs.c
  src/ccow/src/libreptrans/rtrd/reptrans-rd.c
Labels: size/M

#347 efscli object snapshot-rollback support
  src/ccow/include/ccow.h
  src/ccow/src/libccow/snapview.c
  src/efscli/object/snapshot-rollback.go
Labels: approved, size/L

#349 SOP based transaction log
  src/ccow/include/ccow.h
  src/ccow/src/libccow/ccow-impl.h
  src/ccow/src/libccow/sharded-list.c
  src/ccow/src/libccowfsio/fsio_dir.c
  src/ccow/src/libreplicast/replicast.h
  src/ccow/src/libreptrans/reptrans.c
  src/ccow/src/libreptrans/reptrans.h
  src/ccow/src/libreptrans/serial_op.c
  src/ccow/src/libtrlog/trlog.c
  src/ccow/test/sharded_list_test.c
Labels: approved, size/XL

#350 SOP trlog followup fix
  src/ccow/src/libtrlog/trlog.c
Labels: approved, size/XS

#351 Followup fixes for SOP trlog
  src/ccow/src/libflexhash/flexhash.c
  src/ccow/src/libtrlog/trlog.c
Labels: approved, size/S

#353 TRLOG extra errors output
  src/ccow/src/libccowd/trput.c
Labels: approved, size/M

#357 Bypass bucket objects in chunk recovery flow
  src/ccow/src/libccow/named-get.c
Labels: approved, size/XS

#356 Reduce ccowd memory footprint
  src/ccow/src/libccow/ccow-impl.h
  src/ccow/src/libreptrans/rtrd/reptrans-rd.c
Labels: approved, size/S
