Repository Nexenta/edgefs, pull requests merged in 2019-09, with the labels that each got.

#364 make trlog_delete_after_hours configurable again, set it to 3 days by…
  src/ccow/include/ccow.h
  src/ccow/src/libreptrans/reptrans.h
  src/ccow/src/libreptrans/serial_op.c
  src/efscli/config/layout.go
  src/efscli/config/node.go
Labels: approved, size/S

#366 GC background change: skip a parent lookup in split
  src/ccow/src/libreptrans/reptrans.c
Labels: approved, size/XS

#371 Enable select_policy inhereting
  src/ccow/src/libccowfsio/fsio_inode.c
  src/ccow/src/libccowfsio/fsio_system.c
  src/ccow/src/libccowfsio/include/fsio_system.h
Labels: approved, size/S

#370 Rtkvs put fixes
  src/ccow/include/ccowutil.h
  src/ccow/src/libccowd/serverid.c
  src/ccow/src/libreptrans/reptrans-data.c
  src/ccow/src/libreptrans/reptrans-device.h
  src/ccow/src/libreptrans/rtkvs/backend/kvsfs/kvsfs-backend.c
  src/ccow/src/libreptrans/rtkvs/backend/kvslmdb/kvslmdb-backend.c
  src/ccow/src/libreptrans/rtkvs/kvs-backend.h
  src/ccow/src/libreptrans/rtkvs/reptrans-kvs.c
  src/ccow/src/libreptrans/rtlfs/reptrans-lfs.c
  src/ccow/src/libreptrans/rtrd/reptrans-rd.c
  src/ccow/src/libreptrans/rtrd/reptrans-rd.h
  src/ccow/src/libreptrans/unnamed-put.c
  src/ccow/test/Makefile.am
  src/ccow/test/kvs_backend_perf.c
  src/ccow/test/put_file.c
  src/ccow/test/reptrans_standalone_test.c
  src/ccow/test/reptrans_test.c
Labels: approved, size/XXL

#373 Add separate line for segment id to efscli system summary
  src/efscli/system/status.go
Labels: size/XS

#374 RTKVS: preparation work for k8s and rook
  Dockerfile
  src/ccow/src/libreptrans/rtkvs/kvs-backend.h
  src/ccow/src/libreptrans/rtkvs/reptrans-kvs.c
  src/efscli/config/config.go
  src/efscli/config/layout.go
Labels: approved, size/L
