Repository Nexenta/edgefs, pull requests merged in 2019-12, with the labels that each got.

#432 Drop '-s' switch. grpc-nfs supports that switch. Be a pass-thru.
  scripts/edgefs-start.sh
Labels: approved, size/XS

#434 Fix NFS to pickup updates from remote site
  src/ccow/include/ccowfsio.h
  src/ccow/src/libccowfsio/fsio_file.c
  src/ccow/src/libccowfsio/fsio_flusher.c
  src/ccow/src/libccowfsio/fsio_inode.c
  src/ccow/src/libccowfsio/include/fsio_inode.h
Labels: approved, size/L

#436 Fix NFS objects list flow
  src/ccow/src/libccowfsio/fsio_namespace.c
Labels: approved, size/XS

#438 Use "-s" flag to grpc-nfs when starting nfs through edgefs-start.sh.
  scripts/edgefs-start.sh
Labels: size/XS

#440 RTRD init: wait for journal/device symlinks for 10 sec before reporting an error
  src/ccow/src/libreptrans/rtrd/reptrans-rd.c
Labels: size/S

#443 Ignore sync_put option for key/value objects
  src/ccow/src/libccow/putcommon_client.c
Labels: approved, size/S

#448 Unnamed Get performance fix
  src/ccow/src/libccow/ccow-impl.h
  src/ccow/src/libccow/getcommon_client.c
  src/ccow/src/libreptrans/payload-s3.c
  src/ccow/src/libreptrans/payload-s3.h
  src/ccow/src/libreptrans/rtlfs/reptrans-lfs.c
  src/ccow/src/libreptrans/rtrd/reptrans-rd.c
  src/ccow/tools/s3_payload_bench.c
Labels: approved, size/L

#453 Issue 452
  src/ccow/src/libclengine/clengine.c
  src/ccow/src/libclengine/cltopo.c
Labels: size/XS

#451 Extend grpc-proxy service to support cluster and user create requests
  src/efscli/service/delete.go
  src/grpc-efsproxy/Makefile
  src/grpc-efsproxy/cluster/cluster.proto
  src/grpc-efsproxy/cluster/clusterImpl/cluster.go
  src/grpc-efsproxy/efsutil/efsutil.go
  src/grpc-efsproxy/main.go
  src/grpc-efsproxy/service/service.proto
  src/grpc-efsproxy/service/serviceImpl/service.go
  src/grpc-efsproxy/tenant/bucketImpl/bucket.go
  src/grpc-efsproxy/tenant/tenant.proto
  src/grpc-efsproxy/tenant/tenantImpl/tenant.go
  src/grpc-efsproxy/tenant/userImpl/user.go
Labels: approved, size/XXL

#454 Followup fix for grpc-efsproxy
  src/grpc-efsproxy/efsutil/attributes.go
  src/grpc-efsproxy/efsutil/mdutil.go
  src/grpc-efsproxy/efsutil/updatemd.go
  src/grpc-efsproxy/efsutil/user.go
Labels: approved, size/XXL

#456 Add show methods to grpc-efsproxy service
  src/grpc-efsproxy/cluster/cluster.proto
  src/grpc-efsproxy/cluster/clusterImpl/cluster.go
  src/grpc-efsproxy/efsutil/kvutil.go
  src/grpc-efsproxy/service/service.proto
  src/grpc-efsproxy/service/serviceImpl/service.go
  src/grpc-efsproxy/tenant/bucketImpl/bucket.go
  src/grpc-efsproxy/tenant/tenant.proto
  src/grpc-efsproxy/tenant/tenantImpl/tenant.go
Labels: approved, size/L

#458 RTRD: put latency jitter fix
  src/ccow/src/libccow/getcommon_client.c
  src/ccow/src/libreptrans/rtrd/reptrans-rd.c
  src/ccow/src/libreptrans/rtrd/reptrans-rd.h
  src/ccow/test/reptrans_standalone_test.c
Labels: approved, size/L

#460 Free bufferes after file flush. Reduce memory usage by NFS service.
  src/ccow/src/libccowfsio/fsio_flusher.c
Labels: approved, size/XS

#461 warning fixes
  src/ccow/src/libauditd/auditd.c
  src/ccow/src/libccowfsio/fsio_flusher.c
Labels: size/XS

#462 RTRD over S3: parallel delete support
  src/ccow/src/libccow/ccow-impl.h
  src/ccow/src/libccow/putcommon_client.c
  src/ccow/src/libccow/unnamed-put.c
  src/ccow/src/libccowfsio/fsio_inode.c
  src/ccow/src/libreptrans/payload-s3.c
  src/ccow/src/libreptrans/payload-s3.h
  src/ccow/src/libreptrans/rtrd/reptrans-rd.c
  src/ccow/test/reptrans_standalone_test.c
Labels: size/XL
