Repository Nexenta/edgefs, pull requests merged in 2019-07, with the labels that each got.

#301 Enable ACL set through ccowhttpd
  src/ccowhttpd/request.c
Labels: size/XS

#304 centos flock usage fix
  deps/corosync/Makefile
  deps/fio/Makefile
  deps/h2o/Makefile
  deps/jemalloc/Makefile
  deps/json-c/Makefile
  deps/knet/Makefile
  deps/libbacktrace/Makefile
  deps/liberasurecode/Makefile
  deps/libqb/Makefile
  deps/libuv/Makefile
  deps/lmdb/Makefile
  deps/nanomsg/Makefile
  deps/nfs-ganesha/Makefile
  deps/smartmontools/Makefile
  deps/stgt/Makefile
Labels: approved, size/M

#305 fixing incorrect check for system object
  src/efscli/efsutil/printmd.go
Labels: approved, size/XS

#312 Issue #331: a bug in corosync-pod-watcher
  src/corosync-pod-watcher/main.go
Labels: approved, size/XS

#314 detect deleted/empty meta record for mdcache
  src/ccow/src/libreptrans/rtrd/reptrans-rd.c
  src/ccow/test/Makefile.am
Labels: approved, size/S

#317 make sure serverPort is 100 devices apart, do not edit if already set
  src/efscli/config/server.go
Labels: approved, size/XS

#319 GOPATH location changed
  scripts/get-protobuf.sh
  src/Makefile
  src/corosync-pod-watcher/Makefile
  src/efscli/Makefile
  src/grpc-efsproxy/Makefile
  src/grpc-iscsi/Makefile
  src/grpc-nfs/Makefile
  src/grpc-s3/Makefile
  src/grpc-s3x/Makefile
  src/s3gw/Makefile
Labels: approved, size/L

#323 Emergency chunk lookup WIP
  src/ccow/src/libccow/ccow-dynamic-fetch.c
  src/ccow/src/libccow/ccow-dynamic-fetch.h
  src/ccow/src/libccow/unnamed-get.c
Labels: approved, size/M

#327 trlog processing: fetch tenants bug
  src/ccow/src/libtrlog/trlog.c
Labels: approved, size/M

#325 Fix s3x auth and acls
  src/ccow/src/libccow/acl-list.c
  src/ccowhttpd/ccowobj.c
  src/ccowhttpd/libauth/auth.c
  src/ccowhttpd/libauth/auth.h
  src/ccowhttpd/libauth/auth_test.c
  src/ccowhttpd/param.c
  src/ccowhttpd/param.h
  src/ccowhttpd/request_util_test.c
  src/ccowhttpd/sig2auth.c
  src/ccowhttpd/sig4auth.c
  src/grpc-s3x/main.go
Labels: approved, size/XL

#329 Fix s3x v4 authentication for put request
  src/ccowhttpd/ccowobj.c
Labels: size/L

#326 Dockerfile: make edgefs build in containter be working
  Dockerfile
Labels: approved, ok-to-test, size/XS

#333 Fix s3x core dump on parameter list rescale
  src/ccowhttpd/request_util.c
Labels: approved, size/XS

#331 Issue-322: corosync configuration for non-kubernetis env
  scripts/edgefs-start.sh
  src/corosync-pod-watcher/main.go
  src/efscli/config/config.go
Labels: approved, size/L

#334 issue-322-followup
  src/efscli/config/config.go
Labels: size/M
