Repository Nexenta/edgefs, pull requests merged in 2020-04, with the labels that each got.

#530 build fix followup
  Makefile
  deps/samba/Makefile
Labels: size/XS

#531 deep smb integration
  deps/samba/Makefile
  deps/samba/README.md
  deps/samba/smb.conf
  deps/samba/test-bk.conf
  scripts/edgefs-start.sh
  src/Makefile
  src/efscli/bucket/delete.go
  src/efscli/efsutil/attributes.go
  src/efscli/service/create.go
  src/efscli/service/serve.go
  src/efscli/service/service.go
  src/efscli/service/unserve.go
  src/efscli/validate/validate.go
  src/grpc-smb/.gitignore
  src/grpc-smb/Makefile
  src/grpc-smb/export/export.go
  src/grpc-smb/export/export.proto
  src/grpc-smb/main.go
Labels: size/XL

#532 libreptrans: replication on ERC error fix
  src/ccow/src/libreptrans/reptrans.c
Labels: size/XS

#535 Expose interface to used malloc/free methods, so caller can allocate …
  src/ccow/include/ccowfsio.h
  src/ccow/src/libccowfsio/fsio_system.c
Labels: approved, size/S

#538 ecstat updated
  src/ccow/src/libccow/opp-status.h
  src/ccow/src/libreptrans/opp-status-srv.c
  src/ccow/tools/ecstat.c
Labels: approved, size/L

#540 smb: ads join plumbing
  deps/samba/Makefile
  deps/samba/ads-join.sh
  deps/samba/smb.conf
  src/grpc-smb/main.go
Labels: size/L

#545 1. Fixed dsql service to configure for a cluster (few nodes)
  src/ccow/src/libccowfsio/fsio_glm.c
  src/efscli/service/serve.go
  src/efscli/service/unserve.go
  src/efscli/validate/validate.go
  src/grpc-sql/main.go
Labels: approved, size/L

#547 Implement multicluster NFS sync
  src/ccow/include/ccow.h
  src/ccow/include/glm_ops.h
  src/ccow/src/libccow/ccow.c
  src/ccow/src/libccow/sharded-list.c
  src/ccow/src/libccowfsio/fsio_dir.c
  src/ccow/src/libccowfsio/fsio_disk.c
  src/ccow/src/libccowfsio/fsio_glm.c
  src/ccow/src/libccowfsio/fsio_inode.c
  src/ccow/src/libccowfsio/fsio_listcache.c
  src/ccow/src/libccowfsio/fsio_listcache.h
  src/ccow/src/libccowfsio/fsio_recovery.c
  src/ccow/src/libccowfsio/fsio_snapshot.c
  src/ccow/src/libccowfsio/fsio_system.c
  src/ccow/src/libccowfsio/include/fsio_inode.h
  src/ccow/src/libccowfsio/include/fsio_system.h
  src/dqlite/Makefile
  src/dqlite/dqlite.c
  src/dqlite/libdqclient/Makefile
  src/dqlite/libdqclient/dqclient.c
  src/dqlite/libdqclient/dqclient.h
  src/dqlite/libdqclient/geolock.c
  src/dqlite/libdqclient/geolock.h
  src/dqlite/libdqclient/glm_dqlite.c
  src/dqlite/libdqclient/list_geolock.c
  src/dqlite/libdqclient/test_client.c
  src/dqlite/libdqclient/test_geolock.c
Labels: approved, size/XXL

#550 NFS sync followup fix
  src/dqlite/libdqclient/Makefile
  src/dqlite/libdqclient/glm_dqlite.c
Labels: approved, size/XS

#551 NFS sync foolowup fix 2
  src/ccow/src/libccowfsio/fsio_disk.c
Labels: approved, size/S
