Repository Nexenta/edgefs, pull requests merged in 2020-02, with the labels that each got.

#493 Corosync: set mtu=1400 and use udpu network engine
  deps/corosync/corosync.conf.example.ipv4
  src/efscli/config/config.go
Labels: approved, size/XS

#495 Corosync mtu: fixed
  src/efscli/config/config.go
Labels: size/S

#496 ecstat tool: NFS bucket iterator fix
  src/ccow/tools/ecstat.c
Labels: approved, size/XS

#497 Add test that verify sharded list behavior in directory create/readdi…
  src/ccow/test/Makefile.am
  src/ccow/test/sharded_list_basic_fs_dir_test.c
Labels: approved, size/L

#499 follow up fix for sharded_list_basic_fs_dir_test.c
  src/ccow/test/sharded_list_basic_fs_dir_test.c
Labels: size/S

#500 Added stress test for DSQL.
  src/ccow/src/libccowfsio/fsio_file.c
  src/dqlite/dqlite.c
  src/dqlite/libdqclient/Makefile
  src/dqlite/libdqclient/stress_test.c
Labels: size/L

#502 Fix modbit for partial update
  src/ccow/src/libchunk/btree/libbtreecommon/btreecom.c
Labels: approved, size/S

#504 S3 payload: S3 PUT/GET retry on any 5xx response
  src/ccow/src/libreptrans/payload-s3.c
Labels: approved, size/XS

#508 Issue 503 - dqlite global lock
  src/dqlite/libdqclient/Makefile
  src/dqlite/libdqclient/geolock.c
  src/dqlite/libdqclient/geolock.h
  src/dqlite/libdqclient/test_geolock.c
Labels: approved, size/L
