Repository Nexenta/edgefs, pull requests merged in 2020-01, with the labels that each got.

#465 Add key/value support to efscli
  src/ccow/include/ccow.h
  src/ccow/include/ccowutil.h
  src/ccow/src/libccow/ccow-impl.h
  src/ccow/src/libccow/ccow.c
  src/ccow/src/libccow/named-get.c
  src/ccow/src/libccow/put.c
  src/ccow/src/libccow/snapview.c
  src/ccow/src/libccow/unnamed-get.c
  src/ccow/src/libreplicast/replicast.h
  src/efscli/edgex/edgex.go
  src/efscli/edgex/edgex_mockup.go
  src/efscli/edgex/edgex_test.go
  src/efscli/edgex/global.go
  src/efscli/edgex/s3xclient.go
  src/efscli/edgex/util.go
  src/efscli/efsutil/attributes.go
  src/efscli/efsutil/kvutil.go
  src/efscli/efsutil/printlist.go
  src/efscli/keyvalue/create.go
  src/efscli/keyvalue/delete.go
  src/efscli/keyvalue/get.go
  src/efscli/keyvalue/globalcreate.go
  src/efscli/keyvalue/globaldelete.go
  src/efscli/keyvalue/globalget.go
  src/efscli/keyvalue/globallist.go
  src/efscli/keyvalue/insert.go
  src/efscli/keyvalue/keyvalue.go
  src/efscli/keyvalue/list.go
  src/efscli/main.go
  src/efscli/object/get.go
  src/efscli/object/globaldelete.go
  src/efscli/object/globalget.go
  src/efscli/object/globalput.go
  src/efscli/validate/validate.go
Labels: approved, size/XXL

#478 Issue 468
  src/dqlite/Makefile
  src/dqlite/libdqclient/Makefile
  src/dqlite/libdqclient/dqclient.c
  src/dqlite/libdqclient/dqclient.h
  src/dqlite/libdqclient/test_client.c
Labels: approved, size/L

#477 S3 offload utilization separated from disk utilization
  src/ccow/src/libreptrans/reptrans-device.h
  src/ccow/src/libreptrans/reptrans.c
  src/ccow/src/libreptrans/rtrd/reptrans-rd.c
  src/efscli/system/status.go
Labels: size/L

#481 Set connection broker keepalive timeout
  src/ccow/src/libconnbroker/connbroker.c
  src/ccow/src/libconnbroker/connbroker.h
  src/ccow/src/libconnbroker/replicast_broker.c
Labels: approved, size/S

#482 Ecstat nfs support
  src/ccow/src/libccow/opp-status.c
  src/ccow/src/libccow/opp-status.h
  src/ccow/src/libclengine/clengine.c
  src/ccow/src/libreplicast/replicast.c
  src/ccow/src/libreplicast/replicast.h
  src/ccow/src/libreptrans/opp-status-srv.c
  src/ccow/src/libreptrans/reptrans.c
  src/ccow/src/libreptrans/rtrd/reptrans-rd.c
  src/ccow/src/libreptrans/rtrd/reptrans-rd.h
  src/ccow/tools/ecstat.c
Labels: approved, size/XL

#484 Fix efscli summary counts
  src/efscli/system/status.go
Labels: approved, size/M

#486 Add grpc-proxy support for system status and summary
  src/grpc-efsproxy/Makefile
  src/grpc-efsproxy/main.go
  src/grpc-efsproxy/system/system.pb.go
  src/grpc-efsproxy/system/system.proto
  src/grpc-efsproxy/system/systemImpl/system.go
Labels: approved, size/XXL

#491 Disable cache for read in CCOW FSIO. Data already cached by CCOW.
  src/ccow/src/libccowfsio/fsio_cache.c
Labels: approved, size/S
