Repository Nexenta/edgefs, pull requests merged in 2020-03, with the labels that each got.

#516 Added geolocking functionality to NFS.
  src/ccow/include/glm_ops.h
  src/ccow/src/libccowfsio/Makefile.am
  src/ccow/src/libccowfsio/fsio_glm.c
  src/ccow/src/libccowfsio/fsio_inode.c
  src/ccow/src/libccowfsio/fsio_system.c
  src/ccow/src/libccowfsio/include/fsio_inode.h
  src/ccow/src/libccowfsio/include/fsio_system.h
  src/dqlite/Makefile
  src/dqlite/libdqclient/Makefile
  src/dqlite/libdqclient/glm_dqlite.c
Labels: approved, size/XL

#519 Add timezone to system summary
  src/efscli/system/status.go
  src/grpc-efsproxy/system/system.pb.go
  src/grpc-efsproxy/system/system.proto
  src/grpc-efsproxy/system/systemImpl/system.go
Labels: approved, size/L

#526 Fix multicluster NFS stats
  src/ccow/include/ccowfsio.h
  src/ccow/src/libccow/bucket-delete.c
  src/ccow/src/libccowd/trput.c
  src/ccow/src/libccowfsio/fsio_flusher.c
  src/ccow/src/libccowfsio/fsio_system.c
  src/ccow/src/libccowfsio/include/fsio_system.h
Labels: approved, size/L

#525 Geo-locking changes/fixes.
  src/ccow/include/glm_ops.h
  src/ccow/src/libccowfsio/fsio_glm.c
  src/dqlite/libdqclient/glm_dqlite.c
Labels: approved, size/M
